#      ______           _                                       __ 
#     / ____/___ _   __(_)________  ____  ____ ___  ___  ____  / /_
#    / __/ / __ \ | / / / ___/ __ \/ __ \/ __ `__ \/ _ \/ __ \/ __/
#   / /___/ / / / |/ / / /  / /_/ / / / / / / / / /  __/ / / / /_  
#  /_____/_/ /_/|___/_/_/   \____/_/ /_/_/ /_/ /_/\___/_/ /_/\__/  
#   _    __           _       __    __         
#  | |  / /___ ______(_)___ _/ /_  / /__  _____
#  | | / / __ `/ ___/ / __ `/ __ \/ / _ \/ ___/
#  | |/ / /_/ / /  / / /_/ / /_/ / /  __(__  ) 
#  |___/\__,_/_/  /_/\__,_/_.___/_/\___/____/  
#

# ----- Env Variables ----- #
env = XCURSOR_SIZE,24
env = HYPRCURSOR_THEME,CapitaineCursor
env = HYPRCURSOR_SIZE,24

# ----- Preffered Apps ----- #
$terminal = kitty
$fileManager = thunar
$menu = rofi -show drun
$browser = zen-browser