#      __  __                 __                __
#     / / / /_  ______  _____/ /___ _____  ____/ /
#    / /_/ / / / / __ \/ ___/ / __ `/ __ \/ __  / 
#   / __  / /_/ / /_/ / /  / / /_/ / / / / /_/ /  
#  /_/ /_/\__, / .___/_/  /_/\__,_/_/ /_/\__,_/   
#        /____/_/
#

# Monitors
source = $HOME/.config/hypr/configs/monitors.conf

# Autostart
source = $HOME/.config/hypr/configs/autostart.conf

# Environment Variables
source = $HOME/.config/hypr/configs/envVars.conf

# Style
source = $HOME/.config/hypr/configs/style.conf

# Input and Keybinds
source = $HOME/.config/hypr/configs/keyboard.conf

# Window Rules
source = $HOME/.config/hypr/configs/windowRules.conf
