# KITTY WORKFLOW

# Tab bar
tab_bar_edge bottom
tab_bar_margin_width 1
tab_bar_style powerline
tab_powerline_style slanted
tab_bar_align left
tab_bar_min_tabs 2
tab_activity_symbol 󰂠

# Preferences
shell .
editor vim

# Keyboard shortcuts
map alt+h previous_tab
map alt+j close_tab
map alt+k new_tab
map alt+l next_tab
