#   _       __           __   ______             
#  | |     / /___  _____/ /__/ __/ /___ _      __
#  | | /| / / __ \/ ___/ //_/ /_/ / __ \ | /| / /
#  | |/ |/ / /_/ / /  / ,< / __/ / /_/ / |/ |/ / 
#  |__/|__/\____/_/  /_/|_/_/ /_/\____/|__/|__/  
#

# ----- Tab bar ----- #
tab_bar_edge bottom
tab_bar_margin_width 1
tab_bar_style powerline
tab_powerline_style slanted
tab_bar_align left
tab_bar_min_tabs 2
tab_activity_symbol 󰂠

# ----- Preferences ----- #
shell .
editor vim

# ----- Keyboard shortcuts ----- #
map alt+h previous_tab
map alt+j close_tab
map alt+k new_tab
map alt+l next_tab
